language: node_js
branches:
  only:
    - master
jobs:
  include:
    - stage: coverage
      node_js: 8.12.0
      before_install:
        - npm i -g npm@version-number
      script: "npm run coverage"
