language: node_js
branches:
  only:
    - master
jobs:
  include:
    - stage: coverage
      node_js: 8.12.0
      before_install:
        - npm i -g npm@6.4.1
      script: "npm run coverage"
      after_success:
        - bash <(curl -s https://codecov.io/bash) -t $CODECOV_REPO_TOKEN
